### PR TITLE
Adds idpIntegration for prod stable

### PR DESCRIPTION
**Pull request by btarhan**
Hello team,

**Tickets**
closes https://issues.redhat.com/browse/CIAM-8724

**Why**
The CIAM-S AuthN is currently working to provide a self-service 3rd party Identity Provider solution for Red Hat external customers.
CIAM-[ADR-00023](https://issues.redhat.com/browse/ADR-00023?atlOrigin=eyJpIjoiYjM0MTA4MzUyYTYxNDVkY2IwMzVjOGQ3ZWQ3NzMwM2QiLCJwIjoianN3LWdpdGxhYlNNLWludCJ9) Self Service Third Party IdP:
https://docs.google.com/document/d/1nc1Ci1o_dj7qMVWxiW2frTCJEQ4UPB2l_xsnu2zrSoQ/edit#heading=h.ds8q4xtkmu64

our slack channel:
[team-ciam-s-authn](https://redhat.enterprise.slack.com/archives/C04PS3GSJKC)

**NOTE**. Please advise if any other change is needed in order to add a new menu-item.

Thanks!

### CODE REVIEW

**Review by florkbr — COMMENTED** [review]
@btarhan looks good; could you please also update https://github.com/RedHatInsights/chrome-service-backend/blob/main/static/beta/prod/navigation/iam-navigation.json#L180 to include this new navigation link? ~Otherwise this nav item will not show when a prod user enables preview.~

**Comment by btarhan** [comment]
@florkbr Thanks! I can do that now. I was told that the beta folder wasn't in use anymore though, is that not true?

**Comment by florkbr** [comment]
Ah. Sorry @btarhan you are correct - I was thinking this was for a different environment. It's fine to keep the changes to both for now.

**Comment by btarhan** [comment]
@florkbr I updated the MR with the preview part, should I remove that?

**Comment by btarhan** [comment]
That would be great. Thanks! Can you tag with an lgtm?

**Comment by florkbr** [comment]
@btarhan I will; I'm just testing that I see the new nav item on prod when I use this PR locally. One moment.

**Review by florkbr — APPROVED** [review]
@btarhan looks good locally running chrome/chrome service. I see the new nav JSON entry, and the new left nav UI element - though I do not have permissions in prod to make sure the page loads correctly.
Screenshot 2024-09-20 at 10 56 52 AM

LGTM 👍 

We will need to deploy a newer version of chrome service to prod for this change to be picked up after merge. I will coordinate that with my team. Thanks!

**Pull request merged**
