### PR TITLE
feat(RHINENG-9139): rename groups to workspaces

### PR DESCRIPTION
**Pull request by Fewwy**
https://issues.redhat.com/browse/RHINENG-9139

I think this should be merged after we update inventory in this PR
https://github.com/RedHatInsights/insights-inventory-frontend/pull/2213

### CODE REVIEW

**Comment by Fewwy** [comment]
I have found instances like these 
image

in some of the files
What should I do with them

**Review by Hyperkid123 — CHANGES_REQUESTED** [review]
Some of your link references are wrong within the service.json file

```
15:18:58 #27 0.271 go run cmd/services/parseServices.go
15:18:58 #27 0.401 Parsing beta itless
15:18:58 #27 0.403 Parsing beta prod
15:18:58 #27 0.408 panic: unable to find link with id iam.workspaces
```

**Review by Hyperkid123 — APPROVED** [review]

**Pull request merged**
