### PR TITLE
AAP-20248: Admin Dashboard: Production[beta] release

### PR DESCRIPTION
**Pull request by manstis**
See https://issues.redhat.com/browse/AAP-20248

Configures the applicable files for deployment to Production _beta/preview_.

I've submitted a request for the networking side of things here: https://issues.redhat.com/browse/RHCLOUD-30786

Both this JIRA/PR and the reference `RHCLOUD` JIRA are for **PRODUCTION BETA/PREVIEW ONLY**.

### CODE REVIEW

**Review by Hyperkid123 — APPROVED** [review]
LGTM. I've verified the assets are accessible in the beta environment :+1:

**Comment by manstis** [comment]
Thank-you @Hyperkid123 

Most of it works great :tada: 

I however notice that the "Search for services" textbox does not return any results for "lightspeed".

Does the [index](https://github.com/RedHatInsights/chrome-service-backend/blob/main/docs/search-index.md#publishing-search-index) need rebuilding for production?

Here's what _staging_ looks like:

image

**Comment by Hyperkid123** [comment]
@manstis we have to deploy it separately for now. And we only deploy the production stable index. These are current limitations that should go away at some point.

**Pull request merged**
