### PR TITLE
Add config for stage activation keys

### PR DESCRIPTION
**Pull request by jlgre**
This adds the config to use activation-keys-ui's deployment instead of sed-frontend. This is part of the effort to decouple those two applications.

Navigation should not have to change I think - as the routes are staying the same. Just the location of the code is changing.

### CODE REVIEW

**Comment by jlgre** [comment]
@Hyperkid123 do you mind taking a look at this when you have a minute?

**Review by Hyperkid123 — COMMENTED** [review]
The config looks good. I assume the JS assets are not available yet? We can merge this as a prep as it won't really change much until the assets are accessible.

**Comment by jlgre** [comment]
> The config looks good. I assume the JS assets are not available yet? We can merge this as a prep as it won't really change much until the assets are accessible.

The js assets should be available - I have the app deploying to stage already via app-interface. The old app is also still deploying so I'm not totally sure how they will work when they are both deployed, but I have a PR approved and ready to merge to remove the routes for this app so they no longer conflict.

**Comment by Hyperkid123** [comment]
@jlgre the URL currently throws 404. Have you requested Akamai routing changes yet?

**Comment by jlgre** [comment]
I have not - I didn't see that step in the docs. Do you mind pointing me to where the information about that is?

**Comment by justinorringer** [comment]
Hello! here's the doc on it

https://inscope.corp.redhat.com/docs/default/Component/consoledot-pages/containerized-frontends/deploy-stage-and-prod/#akamai-configuration

But really, just clone https://issues.redhat.com/browse/RHCLOUD-25708 for stage, and we will take care of it :)

Here's the one for prod too, for when you have it deployed there https://issues.redhat.com/browse/RHCLOUD-25710

**Comment by jlgre** [comment]
@justinorringer thank you! Cloned!

**Comment by jlgre** [comment]
The assets are in stage now so I believe this should be ready to go - I see the Konflux build is failing but am not sure that has anything to do with my new changes

**Comment by Hyperkid123** [comment]
@jlgre the konflux failure is fine, we have switched konflux namespace while this PR was opened so I think its just confused.

**Review by Hyperkid123 — APPROVED** [review]

**Pull request merged**
