### PR TITLE
OpenShift: Update sidenav IA

### PR DESCRIPTION
**Pull request by jschuler**
Updates the /openshift sidenav

| stable-stage | stable-prod | beta-stage  | beta-prod |
| -------- | ------- | -------- | ------- |
| Screenshot 2024-07-11 at 11 32 07 AM | Screenshot 2024-07-11 at 11 31 52 AM  | Screenshot 2024-07-11 at 11 42 38 AM  | Screenshot 2024-07-11 at 11 50 15 AM |

### CODE REVIEW

**Comment by Hyperkid123** [comment]
@jschuler is there a ticket reference?

**Comment by jschuler** [comment]
@Hyperkid123 yes https://issues.redhat.com/browse/OCMUI-1953

**Comment by Hyperkid123** [comment]
@jschuler I can't do that. This would block other UI modules and the API itself from releasing features to prod. If you want to changes to be visible only in certain environments, you will have to change on relevant files. That is why they exist. This service gets released on a daily basis.

**Comment by jschuler** [comment]
@Hyperkid123 ok, we can just hold merging this PR until then?

**Comment by Hyperkid123** [comment]
@jschuler yup ofc

**Review by Hyperkid123 — APPROVED** [review]

**Pull request merged**
